### PR TITLE
Reopened pull Request for Ranking functionality

### PR DESCRIPTION
**Pull request by aswin98855**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes # <162>

<hr>
 
## Mark the task you have completed ✅

- [✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by aswin98855** [comment]
@Lovelyfin00 

I reopened the pull request. Can you please check it now.

**Comment by aswin98855** [comment]
@Lovelyfin00 

Can you please check it once..Is There any issues still?

**Comment by Lovelyfin00** [comment]
Hey @aswin98855 
Sorry I've been quite busy at work
Will try to review this today

**Comment by Lovelyfin00** [comment]
Hey @aswin98855 
I just pushed from your branch and noticed your PR looks like this

<br/>
<br/>

image

**Comment by Lovelyfin00** [comment]
The css is broken

**Comment by aswin98855** [comment]
@Lovelyfin00 

Now only I checked and verified...I Think it is due to several merges in between the gap 

Can you please verify now

**Comment by aswin98855** [comment]
Should i need to open other pull request or is it sufficient?

**Comment by Lovelyfin00** [comment]
> @Lovelyfin00
> 
> Now only I checked and verified...I Think it is due to several merges in between the gap.
> 
> Can you please verify now

Your changes here are broken. If you're opening a new PR, don't copy and paste what you have here.
Checkout to develop branch, create a new branch and make your changes then open a new PR

**Comment by Durgesh4993** [comment]
@aswin98855 Do one thing reclone the repo and resend the PR

**Pull request closed without merging**
