### PR TITLE
Added hamburger Menu to all the required pages

### LINKED ISSUE #624: [Enhancement]: Better Hamburger-menu
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The Hamburger Menu in the howtoplay page looks very bland.
image

### Describe the solution you'd like

I will make a better menu for smaller screens.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by VijaySamant4368**
## PR Description 📜

I added and/or modified the nav-bar to be consistent in all the following pages:
- About Page
- Contributors Page
- How to Play Page
- FAQs Page

The theme of these pages is totally different, and there is no nav-bar at all in these pages:
- Privacy Policy Page
- Licensing Page
- Terms of Service Page

The **Home screen** layout is not responsive enough for mobile devices,, and I have avoided making any change in it fuee to the following two reasons:
- to avoid possible conflicts.
- the new navbar won't be useable  enough in the current conditions of the home-page

Fixes #624

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>

**Screenshots**

Screenshot 2024-07-26 at 19-30-08 Contributors

Screenshot 2024-07-26 at 19-30-17 How to Play - Dot Box

Screenshot 2024-07-26 at 19-29-59 FAQs

Screenshot 2024-07-26 at 19-29-51 About Us

--- 
<br>

### CODE REVIEW

**Comment by VijaySamant4368** [comment]
Note: The weird behavior of the images in the Contributions page was not caused due to my changes. The problem was already there as the time of the last version of the repo.

**Comment by VijaySamant4368** [comment]
@ayush-t02 please kindly check

**Comment by ayush-t02** [comment]
resolve conflicts

**Comment by ayush-t02** [comment]
why is the hamburger not a part of the navbar?

**Comment by VijaySamant4368** [comment]
@ayush-t02  The hamburger has to be shifted when the side menus is opened, and it will disturb the position of the logo of the website when shifted.

**Comment by VijaySamant4368** [comment]
@ayush-t02 should I change the hamburger position?

**Comment by ayush-t02** [comment]
the hamburger is supposed to be a part of the navbar, in the same line as the logo, look into it if you can otherwise just resolve the conflicts

**Comment by VijaySamant4368** [comment]
@ayush-t02 as I mentioned putting it inside the Nav bar will shift the Nav-bar logo when the side menu opens.
One thing that will look better is inserting the logo inside the side-menu. But it will leave the main nav bar empty in mobile menu.

**Pull request merged**
