### PR TITLE
start button

### LINKED ISSUE #316: [New Feature]: change start button type
### 🎮 feature Request

we can the hover effect of start button it look like old fasion
Screenshot 2024-06-03 225456
i can make a new stylish button

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by puneet426**
Start button in new style

## PR Description 📜

i make a new style animated start button previous button is old version 
Fixes #316 

<hr>
 
## Mark the task you have completed 

https://github.com/ChromeGaming/Dot-Box/assets/168094736/fe9a81cf-3e66-4708-b661-14fbc7b554db

https://github.com/ChromeGaming/Dot-Box/assets/168094736/fe9a81cf-3e66-4708-b661-14fbc7b554db

https://github.com/ChromeGaming/Dot-Box/assets/168094736/fe9a81cf-3e66-4708-b661-14fbc7b554db

✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by puneet426** [comment]
nice

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Resolve conflicts

**Comment by puneet426** [comment]
How to remove conflict

**Comment by puneet426** [comment]
@Durgesh4993

**Comment by puneet426** [comment]
Hello @Durgesh4993 can you please guide me about this because this is my 1st contributions. Can I contact you with what'sapp

**Comment by puneet426** [comment]
hello @Durgesh4993 now i resolve all conflict now you can check it

**Comment by puneet426** [comment]
hello @Durgesh4993 please responce and add  level GSSoC2024

**Comment by puneet426** [comment]
hello @Durgesh4993 now i resolve all issues please check it and merge and close this issue

**Comment by puneet426** [comment]
hello @Durgesh4993 please check it and merge

**Comment by puneet426** [comment]
hello @Durgesh4993 please merge it i complete this project 5 day before and also resolve all issue

**Comment by Durgesh4993** [comment]
@puneet426 i am really apologize for delay due to exam , i have seen you are still using old codes, please check

**Pull request closed without merging**
