### PR TITLE
Srinidhi patch

### LINKED ISSUE #356: [Bug]: Homepage UI can be made responsive for all devices [Majorly mobile] and a detailed instructions can be added
### Give a brief about the bug ✍️

The home page UI is not responsive on mobile phones. 
Instructions are unclear and less for beginners to play the game.
iphone-before
iphone-mini-before
op-nord-2-before
xiaomi-12-before

### What is the expected behavior? 🤔

Home page Can be made responsive for all devices [Majorly for Mobile Phones]The home

### Provide step by step information reproduce the bug 📄

Responsiveness can be made using media queries or using bootstrap
A detailed instructions/rules page can be added separately or on the homepage itself, depending on Project admin instructions.

@Durgesh4993 @ayush-t02  Please assign this issue to me under GSSOC'24 with respective Level  label.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by srinidhifd**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below:
Made all pages responsive on all devices and added instructions.html page for detailed instructions about the game
Fixes #356 

<hr>
 
## Mark the task you have completed ✅

- [ x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x ] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸
-------------------------------------------------BEFORE--------------------------------------------------------------------------
iphone-before
iphone-mini-before
op-nord-2-before
xiaomi-12-before

-----------------------AFTER-------------------------------------------------------------------------------------------------
aftre-fix-1
after-fix-2
after-fix-3
after-fix-4
after-fix-5
after-fix-6
after-fix-7
after-fix-8

--- 
<br>

## Thank you soo much for contributing to our repository 💗

@ayush-t02 I have made the UI of the homepage as well as the game page responsive and added an instructions.html page for detailed instructions. 
I have fixed the bug + an enhancement if possible make it a level 3 issue . Please review this PR.

### CODE REVIEW

**Comment by ayush-t02** [comment]
Conflicts present, please resolve

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Resolve conflict and add a demo video

**Comment by srinidhifd** [comment]
Sir i have raised the issue first , @ayush-t02 sir assigned the issue , the guy who commented on my issue he didn't raise issue also you had merged his PR , I have completed making responsive , Now conflicts have arasied. without raising issue how can his PR get merged ?

**Comment by Durgesh4993** [comment]
@srinidhifd There are no issue kndly check and resolve it

**Pull request closed without merging**
