### PR TITLE
Implemented timer which switches player if the player is inactive for 30 seconds

### LINKED ISSUE #607: [Enhancement]: Adding a 30s timer to next player move
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

If P1 does not move in 30s then the control will go to the next player

### Describe the solution you'd like

If P1 does not move in 30s then the control will go to the next player

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Shreya-1305**
## PR Description 📜
Fixes #607

The timer switches player if the player is inactive for about 30 seconds. The timer automatically resets if the player has make a move and its another player's chance.
<hr>
 
## Mark the task you have completed ✅

- ✅ I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- ✅ I have performed a self-review of my own code or work.
- ✅ I have commented my code, particularly in hard-to-understand areas.
- ✅ My changes generates no new warnings.
- ✅ I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- ✅ I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸
Screenshot 2024-07-25 110706
--- 
<br>

### CODE REVIEW

**Comment by Shreya-1305** [comment]
@ayush-t02 can you please review and tell me if i need to make any changes in this.

**Comment by ayush-t02** [comment]
have you maintained the responsiveness?

**Comment by ayush-t02** [comment]
@Shreya-1305 do not create PR when the issue is not assigned to you

**Comment by Shreya-1305** [comment]
Okay , I am sorry .  I thought I can also contribute to the issue opened by another person.

**Pull request closed without merging**
