### PR TITLE
Add menu

### LINKED ISSUE #72: [New Feature]: Adding Menu
### 🎮 feature Request

feature logic and basic description:
A menu with required buttons on left side

### Point down the features

feature points:
1. Add a menu on the left side for following buttons
2. Home
3. Restart
4. Leaderboard
5. Tournaments

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by hars-21**
## PR Description 📜

Added menu for easy user navigation.  It contains 4 buttons - Home, Leaderboard, Tournament, Settings
Currently functionality was added to home button only as other functions aren't built.
Soon, when others functions will be building they can be added to the buttons.
Fixes #72 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
Screen Shot 2024-05-31 at 9 10 24 PM

Screen Shot 2024-05-31 at 9 10 24 PM

<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by Durgesh4993 — COMMENTED** [review]
Resolve conflict and add demo vedio

**Comment by hars-21** [comment]
https://github.com/ChromeGaming/Dot-Box/assets/144909381/ffc987a2-015c-4c97-8d3e-de4e7aec2f0e

@Durgesh4993 I have resolved the conflicts and please find the attached demo video for fixing the issue.

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Resolve conflicts

**Review by hars-21 — COMMENTED** [review]
Resolved. Please review

**Comment by hars-21** [comment]
@Durgesh4993 Please have a look on PR, there are no merge conflicts. Please merge it.

**Comment by hars-21** [comment]
@Durgesh4993 Conflicts Resolved. Please review my PR.

**Comment by ayush-t02** [comment]
@hars-21 please resolve the conflicts, pull the changes -> add your changes -> push again

**Comment by Durgesh4993** [comment]
@hars-21 you are still using old codes, please check

**Pull request closed without merging**
