### PR TITLE
Solved issue #103- Add the footer 

### LINKED ISSUE #103: [New Feature]: Want to add the footer !
### 🎮 feature Request

I want add the footer with all the social media links of ur  and  adding the copyright at the end of the footer 
Screenshot 2024-05-13 233051
here is the example

### Point down the features

feature points

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below

The issue was to add a footer to the webpage. By including the appropriate HTML markup for the footer element and applying the necessary CSS styling, I ensured that the footer appeared at the bottom of the page. This addition enhances the overall layout and design of the webpage, providing important information or copyright details to the users.

Fixes #103  <your_issue_number>

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸
Screenshot 2024-05-15 012917

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Aditi22Bansal** [comment]
@Durgesh4993 Kindly review it

**Comment by Aditi22Bansal** [comment]
@Durgesh4993 
Kindly review this PR too

**Comment by Aditi22Bansal** [comment]
@Durgesh4993 
Kindly review the PR
I have resolved the conflicts
Thankyou

**Comment by Aditi22Bansal** [comment]
@Durgesh4993 
Kindly review this PR also
Thankyou

**Review by Lovelyfin00 — CHANGES_REQUESTED** [review]
On line 100 in the index.html file, remove the comment there. It shows up in the UI

**Comment by Lovelyfin00** [comment]
Also update your PR by pulling from `develop` branch. And I can't start the game while in your PR. You might have unintentionally broke something

**Comment by Aditi22Bansal** [comment]
done @Lovelyfin00

**Comment by Lovelyfin00** [comment]
And also what you've added here is different from the screenshot you attached in the issue.

**Comment by Aditi22Bansal** [comment]
Ok

**Pull request closed without merging**
