### PR TITLE
Improved how-to-play page

### LINKED ISSUE #569: [Bug]: Unresponsive for mobile devices
### Give a brief about the bug ✍️

The How-To-Play page(/pages/howtoplay.html) looks ugly in mobile view.

### What is the expected behavior? 🤔

Its CSS should be responsive for the mobile too.

### Provide step by step information reproduce the bug 📄

Changing the width of the window, or using Develop tools, we can see observe the How-To-Play page(/pages/howtoplay.html)
image

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by VijaySamant4368**
## PR Description 📜
Improved the how-to-play page by adding a navbar toggler

Fixes #569

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by VijaySamant4368** [comment]
image_2024-07-22_191629695

**Comment by VijaySamant4368** [comment]
@ayush-t02 Please check and merge

**Comment by ayush-t02** [comment]
What is the change done here exactly? I believe hamburger navbar is already present

**Comment by ayush-t02** [comment]
Add this hamburger to the navbar for all the pages not just one

**Comment by VijaySamant4368** [comment]
@ayush-t02 many other pages don't require it.
There are no nav-bar items in these pages:
- Licensing
- Privacy Policy
- Terms of Service
- Game
- FAQ
- Contributors

The only page that should include the hamburger and doesn't already is **about page**, which I will improve right now.
Also there is a hamburger menu in the **home page**, with a slight error, which I will resolve.

If I have missed something, please do tell me.

**Comment by VijaySamant4368** [comment]
In home page, the wired behavior starts at 768px and and remains like that as we reduce the width. The webpage becomes scrollable, therefore the hamburger doesn't appear at first, but if we scroll left, we can see that the hamburger is at the far right of the nav-bar.

**Comment by VijaySamant4368** [comment]
@ayush-t02  Can I get a level 3?

**Comment by ayush-t02** [comment]
Not for this PR

**Pull request merged**
