### PR TITLE
404 not found page added

### LINKED ISSUE #258: [New Feature]: create a 404 not found page for the website
### 🎮 feature Request

create a 404 not found page for the website

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
## PR Description 📜

404 not found page added

Fixes #258 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@Durgesh4993 please review the PR

**Comment by RamakrushnaBiswal** [comment]
@ayush-t02 check the Pr

**Comment by RamakrushnaBiswal** [comment]
@ayush-t02 add assignee

**Comment by RamakrushnaBiswal** [comment]
@ayush-t02 just added the page but if you not give me assignee then they didn't give me points🥹🥲

**Comment by ayush-t02** [comment]
@RamakrushnaBiswal you need to add some use case atleast, just the page is redundant

**Pull request merged**
