### PR TITLE
Fixed and Enhance Working of The Cursor Trail Effect

### LINKED ISSUE #496: [Bug]: The Cursor Trail Effect Has Stopped Working
### Give a brief about the bug ✍️

Hey @ayush-t02 

The cursor trail effect has stopped working and is not moving, I would like to Re-create the trail effect for the website which matches to the website design theme and will increase the UI/UX

image

https://github.com/user-attachments/assets/0c473070-aad5-4e9b-ac6c-18e0375e64e2

### What is the expected behavior? 🤔

The trail effect should work smoothly and also it should work fine across all pages without hindering any part of the website or  game

### Provide step by step information reproduce the bug 📄

move the cursor

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by MastanSayyad**
## PR Description 📜

Hey @ayush-t02 

- Fixes #496

I have fixed the working of the cursor trail effect

- Added new cursor trail effect
- Effect has radial gradient color of `#49e8f7` and `#8d26ac`
-  The CSS and HTML files have been updated to support this change in `index.html`
- The **Trail effect** smoothly **synchronizes** with the cursor movement.
          - The `mousemove` event listener adjusts for the vertical scroll position using `window.scrollY.`
          - The circles' positions are updated in the `animateCircles` function, ensuring they follow the cursor with a trailing effect.
- It works fast and smoothly across all pages.

https://github.com/user-attachments/assets/841dd647-f990-43c9-b317-2cff2f3f54d1

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by ayush-t02** [comment]
Resolve conflicts

**Comment by MastanSayyad** [comment]
@ayush-t02 I have resolved the conflicts!

**Comment by MastanSayyad** [comment]
Hey @ayush-t02 Please merge this PR

**Comment by ayush-t02** [comment]
game.html has conflicts, please resolve

**Comment by MastanSayyad** [comment]
@ayush-t02 I have resolve the conflicts please merge it!

**Pull request merged**
