### PR TITLE
Fixed the feedback form for 480px

### LINKED ISSUE #683: [Bug]: Feeback form is not responsive to smaller screen
### Give a brief about the bug ✍️

image

### What is the expected behavior? 🤔

It should not overflow in 480px

### Provide step by step information reproduce the bug 📄

index.html > feedback

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by ayush-848**
## PR Description 📜
Fixed the feedback form for 480px

Fixes #683

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by ayush-848** [comment]
@ayush-t02 please check

**Comment by ayush-t02** [comment]
add the submit and reset button in the pop up menu

**Comment by ayush-848** [comment]
> add the submit and reset button in the pop up menu

Ok

**Comment by ayush-848** [comment]
image
@ayush-t02 done

**Pull request merged**
