### PR TITLE
Adding title and change colors of form-item

### PR DESCRIPTION
**Pull request by Ipeeka**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes # <your_issue_number>

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Ipeeka** [comment]
Adding title and change colors of form-item

**Comment by Durgesh4993** [comment]
@Ipeeka Please add issue number and resolve conflicts

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Add issue number

**Comment by TanviPoddar** [comment]
Please assign this issue to me as I have previous experience with HTML, CSS and Javascript. I'll try my best to resolve it!

**Pull request closed without merging**
