### PR TITLE
Adding Chatbot and home icon to every Page

### LINKED ISSUE #512: [New Feature]: Adding Chatbot and home icon to every Page
### 🎮 feature Request

@ayush-t02 I want to add chatbot to website and home icon to every Page . Kindly assign this issue to me. 

### Point down the features

This allows to ask questions and navigate easily to main page.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Ojas-Arora**
## PR Description 📜

@ayush-t02 I have again made the changes for the same issue without any conflicts. Kindly review this.
Fixes #512 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by ayush-t02** [comment]
I dont see any chatbot on my end, add a demo video

**Comment by Ojas-Arora** [comment]
@ayush-t02 ok

**Comment by ayush-t02** [comment]
pull all the recent changes then record the video

**Comment by Ojas-Arora** [comment]
@ayush-t02 I think it is not present in the main Page . I will pull all the recent changes along with the chatbot in the main Page

**Comment by ayush-t02** [comment]
create a new PR and fix it

**Comment by Ojas-Arora** [comment]
@Ojas-Arora ok

**Comment by MastanSayyad** [comment]
@ayush-t02 Make sure you remove Level 3 tags from both PRs that got reverted (As you have gave him level 3 tag for new issue for the same chatbot functionality) otherwise he will get 90 points on the leaderboard for both the failed PRs

**Comment by ayush-t02** [comment]
@MastanSayyad noted

**Comment by Ojas-Arora** [comment]
@ayush-t02 Sir I should get atleast  level 3 for one and for another I should get another level because I am have worked  on 2 issues one is the making of the chatbot and home icon and second is adding chatbot in home page and setting other pages.

**Comment by MastanSayyad** [comment]
> @ayush-t02 Sir I should get atleast level 3 for one and for another I should get another level because I am have worked on 2 issues one is the making of the chatbot and home icon and second is adding chatbot in home page and setting other pages.

First of all @Ojas-Arora The chatbot you're adding is not custom-coded, it is inbuilt powered by Tidio, (similar to Botpress). and Yes, you are getting a level 3 as @ayush-t02 already assign a new issue #549  worth level 3,

Its your responsibility to add the chatbot across all pages to maintain consistency, you cant get level 3 for this, It is unfair to all other contributors!  I hope you get it!

**Comment by Ojas-Arora** [comment]
> > @ayush-t02 Sir I should get atleast level 3 for one and for another I should get another level because I am have worked on 2 issues one is the making of the chatbot and home icon and second is adding chatbot in home page and setting other pages.
> 
> First of all @Ojas-Arora The chatbot you're adding is not custom-coded, it is inbuilt powered by Tidio, (similar to Botpress). and Yes, you are getting a level 3 as @ayush-t02 already assign a new issue #549 worth level 3,
> 
> Its your responsibility to add the chatbot across all pages to maintain consistency, you cant get level 3 for this, It is unfair to all other contributors! I hope you get it!

@MastanSayyad I think we should leave it to mentor @ayush-t02 to decide. 
I have not reverted the PR and he had himself asked to do the changes again so what about the work I have done previously. And Let's not get into what is fair and unfair for contributors !! 
@sanjay-kv Kindly look into this and provide me an update for the same.

**Comment by Ojas-Arora** [comment]
@MastanSayyad  By the way, does it really matter if the chatbot I added is custom-coded or built-in? 
I think it is for Project Admin to decide whether they require custom-coded chatbot or inbuilt one . If the inbuilt chatbot fulfils the requirement of Project Admin @ayush-t02 then I feel it's worth it.
If the contributor and PA doesn't have any issue on this, then I guess @MastanSayyad you are no one to interfere.

**Comment by MastanSayyad** [comment]
@Ojas-Arora I don't have any objections but GSSoC is all about fairness, we have to get into it! this is how gssoc works!  if you are getting 90 points for the same issue which is not even working successfully and breaking the existing Ui plus again you are getting a level 3 for the same newly genrated issue then you will get total 135 points for the same! if you think its right then its fine 

And yes if it is fulfilling the requirement of the PA then you have the responsibility to test and debug before making the PR, Its your work, if it hurts you then sorry for the interference from my side! I'll let @sanjay-kv and @ayush-t02 to handle it! 

Happy Contributing!

**Comment by ayush-t02** [comment]
@Ojas-Arora if your PR doesn't do the job, no level will be assigned. Let me make it clear to you, I will not benefit by giving or taking away the label, this program is all about learning about open-source. 

rule no 1 is to maintain a decorum and take responsibility of your actions. Your PRs produced a glitch in the project and hence they were reverted, a reverted PR does not count no matter. It is quite normal for this to happen, no need to worry.

both @Ojas-Arora @MastanSayyad please maintain a decorum and do not spam replies of github issues or PR. any and all matters should be talked out on the discord server or dm me personally.

**Comment by sanjay-kv** [comment]
sc
here is your contribution list

**Comment by Ojas-Arora** [comment]
@sanjay-kv Thank you sir for providing my contribution list for GSSoC 2024. Your support and guidance have been invaluable to my open-source journey.

**Pull request merged**
