### PR TITLE
Fixed The Broken UI of Home Page 

### LINKED ISSUE #621: BUG: The Home Page UI is Broke
### Give a brief about the bug ✍️

Hey @ayush-t02 

On this website the home page UI is broke

image

### What is the expected behavior? 🤔

N/A

### Provide step by step information reproduce the bug 📄

N/A

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
## PR Description 📜
Hey @ayush-t02 

- issue closes #621 

I have Fixed the Broken UI of the Home Page

## Before

image

## After 

image

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for review.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by RadhikaMalpani1702** [comment]
Hey @ayush-t02 If possible could you please increase the level of this PR ?

**Comment by Lovelyfin00** [comment]
Nice work @RadhikaMalpani1702 
But the content should be scrollable since the header is fixed.
<br/>
<br/>

image

**Comment by RadhikaMalpani1702** [comment]
@Lovelyfin00 In my screen it is fit to the screen that's why I didn't make any changes as it was like this before  

image

please make sure your screen size is 100% for browser window!

**Comment by RadhikaMalpani1702** [comment]
@ayush-t02 If possible could you please increase the level as the trail effect and some footer links are also not working

**Comment by ayush-t02** [comment]
not for this PR, also the font seems to be reversed as well which was changed via a different PR, did you rollback to a previous commit state?

**Comment by RadhikaMalpani1702** [comment]
@ayush-t02 No, I just referred and change them from other pages as the font style was not consistent

**Pull request merged**
