### PR TITLE
refactor: Made settings (index.html) page responsive, Seperate settin…

### LINKED ISSUE #237: [Bug]: Dot-Box game is not at all responsive for mobile  devices
### Give a brief about the bug ✍️

Description
The Dot-Box game is not at all responsive for mobile devices.

Screenshot (296)

### What is the expected behavior? 🤔

Description
The Dot-Box game must have been responsive, and adaptive to all type of mobile screen sizes 

### Provide step by step information reproduce the bug 📄

Description

Open the site: [https://gamesphere-multiplayer.github.io/Dot-Box/](https://gamesphere-multiplayer.github.io/Dot-Box/) in a mobile device

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### Urgency (Optional)

High priority

### PR DESCRIPTION
**Pull request by mondalsurojit**
## PR Description 📜

📌 refactor: Made settings (index.html) page responsive 
📌 Seperated game.html from settings (index.html)
📌 Created seperate CSS files, to avoid any possible conflicts
📌 Going back to the settings page is possible after a match. It was earlier not possible.
📌 favicon fixed

Fixes #237 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

Desktop:
Screenshot (309)
Screenshot (313)

Mobile:
Screenshot (310)
Screenshot (311)
Screenshot (312)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by mondalsurojit** [comment]
@Durgesh4993 Please review my PR...

**Review by Durgesh4993 — COMMENTED** [review]
@mondalsurojit Resolve conflict files and add demo video

**Comment by mondalsurojit** [comment]
@Durgesh4993 In the main branch, which is in sync with the original branch, when I pulled the latest changes, by other contributors, I found that several of the features are not working, like the Exit button, or the rank chart....

So what should I do, should I merged it like that only...? Or should I raise another issue, to fix all of those pseudo features...?

Current version: Several of the contributions are just pseudo, there is absolutely NO functionality attached with it, just simple changes done in the UI...Please go the video, you will get it
[https://youtu.be/CqsJ7gw5tiM](url)

My version: 
[https://youtu.be/UczvESNf7e8](url)


If I have your permission, then I will eliminate all the unwanted changes done by others, in this project...It will also solve all the unnecessary merge conflicts....

**Comment by Durgesh4993** [comment]
@mondalsurojit do one thing reclone the repository and then send the PR

**Pull request closed without merging**
