### PR TITLE
Added Play Again and Exit Buttons

### LINKED ISSUE #240: Bug : No Exit Button or Play Again Button After Finishing The Game!!
### Give a brief about the bug ✍️

@Durgesh4993
In This Section, There Is Now Way For Exiting The Game After The Game Gets Ended Up!!
So, I wanna Add an **Exit Section** For This as well as **Play Again** Button Too.
Please Assign me This Task For GSSOC'24.
Screenshot 2024-05-26 114741

### What is the expected behavior? 🤔

Add An **Exit** Button and **Play Again** Button Right Below The The Grid To Exit From The Game or Start a new Game.

### Provide step by step information reproduce the bug 📄

Create an another Container Which contains Exit and Play Again Button, Which Pops Up after 2 - 3 Seconds Right After The Game Gets Ended Up.
If You Click The Exit Button It will Take you To The Home Page.
If You Click The Play Again Button It will Clear all the Points Table and Box Filling's.(Need some more JavaScript Here).

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by tanishaprasad**
## PR Description 📜

I have added the Play Again and Exit buttons and aligned them with the mute button . 
Fixes #240 <Issue #240>

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

Screenshot 2024-05-31 140143

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Lovelyfin00** [comment]
Hi @tanishaprasad 
Thanks for contributing to the project
Include a screenshot or video recording and fix the merge conflicts

**Comment by tanishaprasad** [comment]
> Hi @tanishaprasad Thanks for contributing to the project Include a screenshot or video recording and fix the merge conflicts

@Lovelyfin00 I have added the screenshot and fixed the merge conflicts.

**Comment by Lovelyfin00** [comment]
Just a quick suggestion
Play again button should only show when the game has ended

**Comment by Lovelyfin00** [comment]
The styling is broken
And also check the inputs
It repeats. I think your fixing of merge conflicts broke something
<br/>
<br/>

image

**Comment by tanishaprasad** [comment]
> The styling is broken And also check the inputs It repeats. I think your fixing of merge conflicts broke something
> 
> image
@Lovelyfin00 I have tried to fix the Styling.

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
There are some conflicts in file could you please reclone the repo and then send PR again

**Pull request closed without merging**
