### PR TITLE
Time limit functionality added

### LINKED ISSUE #105: [Enhancement]: Add time limit for each player's turn
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

For each player's turn there is no limit which may lead to time wastage. 

### Describe the solution you'd like

To manage time, we can add time limit for each player's turn using javascript. This will ensure that player completes his move within specified time and if not, another player's turn starts.

### Select program in which you are contributing

GSSoC'24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

please assign this issue to me under GSSoC'24.

### PR DESCRIPTION
**Pull request by ankiiitagupta**
# PR Description 📜
Added time limit functionality so that the players  don't have to wait much for their turn. In this, a time limit of one minute has been added and ,in case , the player runs out of time, a time's up dialog box appears and next player can play their turn.

Fixes #105 

## Mark the task you have completed

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for review.

#demo video

https://github.com/ChromeGaming/Dot-Box/assets/108889476/2cf4eac3-6fc9-4de0-aed4-0f54b116a10b

### CODE REVIEW

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Add a demo video and resolve conflict file

**Comment by ankiiitagupta** [comment]
hey, sorry for this. I have made changes as specified, you can check it now

**Comment by Durgesh4993** [comment]
@ankiiitagupta Add a demo video

**Comment by ankiiitagupta** [comment]
I already added it in PR. If it is not visible to you, here's a demo video

https://github.com/ChromeGaming/Dot-Box/assets/108889476/3c28a291-41b9-40af-b46a-4a80f98d8496

**Comment by ankiiitagupta** [comment]
@Durgesh4993 Can you review it and let me know if any changes has to be made.

**Comment by Durgesh4993** [comment]
@ankiiitagupta you are still using old codes

**Pull request closed without merging**
