### PR TITLE
Create Contributing.md

### LINKED ISSUE #106: Missing CONTRIBUTION.md file
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

### PR DESCRIPTION
**Pull request by deekshithapalla**
## PR Description
I've created Contributing.md file and added necessary details which're required to be followed in-order to contribute.

Fixes #106

<hr>
 

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)

### CODE REVIEW

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Update on our coduofconduct file

**Comment by deekshithapalla** [comment]
I Didn't get you. Can u pls brief about, where to make changes?

**Comment by Durgesh4993** [comment]
@deekshithapalla Instead of creating new Contributing.md  file you should do changes on "https://github.com/ChromeGaming/Dot-Box/blob/main/.github/CONTRIBUTING_GUIDELINE.md"

**Comment by deekshithapalla** [comment]
#309 please check this once.

**Pull request closed without merging**
