### PR TITLE
separated the css from the html files

### LINKED ISSUE #673: [Bug]: HTML files have css code even though style is a different folder
### Give a brief about the bug ✍️

All the CSS should be part of the style folder with proper naming as to which file contains which css

### What is the expected behavior? 🤔

All the CSS should be part of the style folder with proper naming as to which file contains which css

### Provide step by step information reproduce the bug 📄

simply open index.html

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by ayush-848**
Fixes #673

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by ayush-848** [comment]
@ayush-t02 can you check it from your end. I noticed some html had 3-4 style tag inside them. When I cleaned them everything was good in my server.

**Comment by ayush-t02** [comment]
I think in certain files css is removed but not the style tag

**Comment by ayush-848** [comment]
> I think in certain files css is removed but not the style tag

Yes. Let me fix it

**Comment by ayush-848** [comment]
@ayush-t02 now check it

**Pull request merged**
