### PR TITLE
User can add names instead of player name and improve the UI.

### PR DESCRIPTION
**Pull request by lakshay-porwal**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #156

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Lovelyfin00** [comment]
Include screenshot or video recording of your fix

**Comment by lakshay-porwal** [comment]
> Include screenshot or video recording of your fix

Hi,

I've made the fixes. Attached are the screenshots and video recording showing the changes.

Let me know if you need anything else.

Screenshot 2024-05-21 162306
Screenshot 2024-05-21 162145

https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/150954274/f02a736f-578f-4274-8826-72ec47353521

**Comment by Lovelyfin00** [comment]
Hi @lakshay-porwal 
This looks really good
Just a few suggestions
The player names should show up as an input. Maybe you can have a checkbox or a switch that ask them if they want to customize their names.
If they check yes, then you can display input text depending on the number of players they entered.
Also when the game has ended, remove the alert dialog that you added


NOTE: PRs are meant to be merged to `develop` branch not `main`

**Comment by Lovelyfin00** [comment]
If you already created an issue for this PR, indicate it in the description by adding the issue number. If not, create an issue and link it here

**Comment by lakshay-porwal** [comment]
> If you already created an issue for this PR, indicate it in the description by adding the issue number. If not, create an issue and link it here

Hi @Lovelyfin00 
Just wanted to drop a huge thank you for your awesome suggestions! 😊 I've applied them in the code and created PR #275. Your help means a lot!

Here's a screenshot to give you a glimpse of the changes.
Screenshot 2024-05-31 235056
Screenshot 2024-05-31 235037


Warm regards, 
Lakshay Porwal

**Pull request closed without merging**
