### PR TITLE
Made navbar responsive and transparent background  issue #374

### LINKED ISSUE #374: [Bug]: Navbar fixes - responsiveness and color
### Give a brief about the bug ✍️

The current navbar is not responsive. I propose to make the navbar responsive and also make it transparent (change the font color for links for better viewing)

### What is the expected behavior? 🤔

1. Navbar is responsive - doesnt overlap with any content
2. Navbar is transparent with proper color shades for links. 

### Provide step by step information reproduce the bug 📄

The bug is clearly visible when inspected in the browser.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by HarshitGupta1511**
## PR Description 📜

Made navbar responsive and its background transparent , made links better by adding transition , due to the complete game homepage the title "Maximise boxes" was overlapping to the other links of navbar , so to change that we need to completely change the homepage , so i made navlinks display to none for the smallest screen (that was the best solution I found), clearly visible upto the tablet screen , attaching images of all cases for your reference 
Fixes #374 

<hr>
 
## Mark the task you have completed ✅

- [x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [ x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸
Issue
Screenshot 2024-06-21 at 7 49 37 PM

solution:
laptop screen
Screenshot 2024-06-21 at 7 48 02 PM

tablet screen
Screenshot 2024-06-21 at 7 48 25 PM

phone screen
Screenshot 2024-06-21 at 7 48 40 PM

added hover effect
Screenshot 2024-06-21 at 7 55 11 PM
Screenshot 2024-06-21 at 7 55 19 PM

### CODE REVIEW

**Comment by HarshitGupta1511** [comment]
please review and merge my PR @ayush-t02

**Comment by HarshitGupta1511** [comment]
please review @ayush-t02

**Comment by HarshitGupta1511** [comment]
sir why checks failed, my changes do not change anything else in the game
@ayush-t02

**Comment by ayush-t02** [comment]
@HarshitGupta1511 as long as there are no merge conflicts its fine

**Comment by HarshitGupta1511** [comment]
@ayush-t02 sir 
can I get the reason for closing PR without merging it?

**Comment by ayush-t02** [comment]
actually you closed the PR yourself by deleting the head repo.

**Pull request closed without merging**
