### PR TITLE
Home page enhancement ~ harshcodesit

### LINKED ISSUE #116: Homepage UI black and white very plain and basic
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The homepage looks very simple and blank , also it is black and white so makes it look more dull

### Describe the solution you'd like

I love working with UI and will surely make your homepage look more attractive and stylish, the first look and feel of webiste will completely enhance, kindly assign to me under gssoc'24

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by harshcodesit**
## PR Description 📜

enhancement of home page UI and "start form"

Fixes #116

<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅] I have performed a self-review of my own code or work.
- [ ✅] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [ ✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

Screenshot 2024-05-28 203730

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by harshcodesit** [comment]
@Durgesh4993 please check the PR and merge the contribution

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Could you please change this image into relatable image for game and don't forget to resolve conflict

**Comment by Durgesh4993** [comment]
@harshcodesit There are multiple conflict between files you can reclone the repo

**Comment by harshcodesit** [comment]
ok sir I'll resolve the conflicts

**Pull request closed without merging**
