### PR TITLE
Add new feature : Restart button and home button added

### LINKED ISSUE #194: [New Feature]: add restart button & Home button & How to play section
### 🎮 feature Request

add restart button after game start so that user can restart if needed , and home button for back to return home page.

### Point down the features

add restart button after game start so that user can restart if needed 
home button for back to return home page.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Vipullakum007**
## PR Description 📜

There is not home button and restart button on game page i have solved issue and added home button and restart button.
Fixes #194

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸
Screenshot 2024-05-22 093609

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Vipullakum007** [comment]
hey @Lovelyfin00  , conflicts are resolved sorry for late ,i have forgot about this PR

**Comment by Vipullakum007** [comment]
> hey @Lovelyfin00 , conflicts are resolved sorry for late ,i have forgot about this PR

hey @Lovelyfin00 , please review it.

**Comment by Vipullakum007** [comment]
hey @Lovelyfin00 , why this PR not shown on leaderboard can you check?

**Comment by Lovelyfin00** [comment]
> hey @Lovelyfin00 , why this PR not shown on leaderboard can you check?

We're taking a look at this

**Comment by Lovelyfin00** [comment]
Hi @Vipullakum007 
Only merged PRs are counted

**Pull request closed without merging**
