### PR TITLE
Loader fix

### PR DESCRIPTION
**Pull request by hars-21**
## PR Description 📜

Fix the previous bug in loader script.
Fixes # <your_issue_number>

<hr>
 
## Mark the task you have completed ✅

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by ayush-t02** [comment]
use the PR template properly

**Comment by ayush-t02** [comment]
also add a demo video with proper functioning

**Comment by hars-21** [comment]
https://github.com/ChromeGaming/Dot-Box/assets/144909381/4a892086-c3eb-477e-a7fe-63c18be6ce15

@ayush-t02 Please review the attached demo video.

**Comment by ayush-t02** [comment]
1. some conflicts are present, please resolve them
2. reduce the duration of the loader
3. use a different loader if possible, probably something that matches the colour scheme of the webpage.

**Pull request closed without merging**
