### PR TITLE
Navbar & Footer updated

### LINKED ISSUE #681: [Bug]: Navbar not working in mobile view
### Give a brief about the bug ✍️

Description

The navbar in mobile contains broken links that generates error when clicked.
The hamburger menu is also not aligned.
The hamburger menu is not visible on home page.

### What is the expected behavior? 🤔

Description

The navbar should not have broken links
Menu to be aligned
Menu to be visible on home page

Screen Shot 2024-08-03 at 1 27 43 PM
Screen Shot 2024-08-03 at 1 28 04 PM
Screen Shot 2024-08-03 at 1 28 34 PM
Screen Shot 2024-08-03 at 1 28 41 PM

### Provide step by step information reproduce the bug 📄

Description

Change navbar links to new one
Align and make the menu visible

### Select program in which you are contributing

Gssoc'24

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by hars-21**
## PR Description 📜

Successfully Updated the navbar and footer.
common code for every page
rendered navbar and footer on every page
It includes recently added testimonial page

Fixes #681  #705 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

Screen Shot 2024-08-09 at 5 34 41 PM
Screen Shot 2024-08-09 at 5 34 47 PM
Screen Shot 2024-08-09 at 5 34 53 PM
Screen Shot 2024-08-09 at 5 50 52 PM

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by ayush-t02** [comment]
resolve conflicts

**Comment by hars-21** [comment]
@ayush-t02 Resolved!! Please review

**Comment by ayush-t02** [comment]
@hars-21 there are a lot of conflicts as of now

**Comment by hars-21** [comment]
@ayush-t02 I have resolved the merge conflicts. Please review

**Comment by hars-21** [comment]
Also, there are new issues regarding the same

**Comment by hars-21** [comment]
@ayush-t02 But you assigned level3 as 2 issues were addressed

**Comment by ayush-t02** [comment]
Both issues go hand in hand, updating navbar and footer is essentially redundant because what can you change now?

And responsiveness is an inherent part of all the work you do as a web developer and shouldn't be considered a separate issue.

**Comment by hars-21** [comment]
Please, as issue was given level 3 that's why I asked for level 3.

**Comment by ayush-t02** [comment]
Pin the issue please

**Comment by hars-21** [comment]
Thanks!!!!

**Pull request merged**
