### PR TITLE
Adding Chatbot and home icon to every Page

### LINKED ISSUE #512: [New Feature]: Adding Chatbot and home icon to every Page
### 🎮 feature Request

@ayush-t02 I want to add chatbot to website and home icon to every Page . Kindly assign this issue to me. 

### Point down the features

This allows to ask questions and navigate easily to main page.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Ojas-Arora**
## PR Description 📜

@ayush-t02 I have added the chatbot and the Home icon to every Page. Kindly review this.
Fixes #512 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by ayush-t02** [comment]
add a demo video

**Comment by Ojas-Arora** [comment]
@ayush-t02 I don't know how to make the video of my changes but I can tell what all changes i have done

**Comment by ayush-t02** [comment]
just share a screen recording and resolve the conflicts

**Comment by Ojas-Arora** [comment]
@ayush-t02 I have resolved the conflicts and also added the screen recording. Kindly review this.

https://github.com/user-attachments/assets/0b5ebd61-4db1-4239-b653-6974fb2a6d78

**Comment by ayush-t02** [comment]
does the chatbot work?

**Comment by ayush-t02** [comment]
I'll merge it as of now but if anything breaks due to this PR I'll revert it.

**Comment by Ojas-Arora** [comment]
@ayush-t02 Yes the chatbot works perfectly

**Comment by Ojas-Arora** [comment]
@ayush-t02 Sir I should get atleast level 3 for one and for another I should get another level because I am have worked on 2 issues one is the making of the chatbot and home icon and second is adding chatbot in home page and setting other pages.

**Pull request merged**
