### PR TITLE
Menu

### PR DESCRIPTION
**Pull request by hars-21**
## PR Description 📜

Added Settings Menu with various options:
1. Home button
2. Leaderboard Button
3. help -> It will trigger the tour guide and the timer will be stopped.
4. restart button with animation
5. Sound toggle
6. A timer with enhanced UI and it also turns red when timer is below 10 seconds.

Fixes # <your_issue_number>

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

Screen Shot 2024-08-05 at 4 06 57 PM
Screen Shot 2024-08-05 at 4 07 04 PM
Screen Shot 2024-08-05 at 4 07 23 PM
Screen Shot 2024-08-05 at 4 07 37 PM

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by hars-21** [comment]
Screen Shot 2024-08-05 at 4 10 47 PM
Screen Shot 2024-08-05 at 4 10 55 PM
Screen Shot 2024-08-05 at 4 11 20 PM
Screen Shot 2024-08-05 at 4 11 24 PM


It is responsive as well

**Comment by hars-21** [comment]
@ayush-t02 Please review!

**Comment by ayush-t02** [comment]
does this PR have any specific issue?

**Comment by hars-21** [comment]
#72

**Pull request merged**
