### PR TITLE
Corrected only the header and footer for screens wider than 400px

### LINKED ISSUE #586: [Bug]: Home page layout on smaller screens
### Give a brief about the bug ✍️

The nav-bars are working fine for any width of screens, but the body contents themselves are a mess, and therefore mess up the whole page.

### What is the expected behavior? 🤔

They should display good CSS.

### Provide step by step information reproduce the bug 📄

Home page for:
- Home screen of width 768px and less
image

-Home screen with width between 769px and 1166px, insclusive
image

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by VijaySamant4368**
## PR Description 📜

The issue is not still fully resolved, but I made this pr to ask for opinions till this point, so that, if required, changes can be made.
Fixes #586 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by VijaySamant4368** [comment]
When the width is less than 1100px, the following links go inside hamburger:
- Home
- About Us
- FAQs
- Contributions
- Let's Go
- How to Play
- Terms of Service
- Privacy Policy Licensing

Furthermore, the Feedback button on the side, shifts to the footer area

https://github.com/user-attachments/assets/c551ee32-a648-4ca7-b438-3cb6ca607ce2

**Comment by VijaySamant4368** [comment]
At 625px, the Discord and Github links go inside the hamburger menu.
At 500px, the Feedback button also go inside the Hamburger menu.

https://github.com/user-attachments/assets/7efb2cf6-4396-4a18-8370-befdf8a5f4a4

**Comment by VijaySamant4368** [comment]
@Lovelyfin00 please have a look

**Comment by Lovelyfin00** [comment]
> When the width is less than 1100px, the following links go inside hamburger:
> 
> * Home
> * About Us
> * FAQs
> * Contributions
> * Let's Go
> * How to Play
> * Terms of Service
> * Privacy Policy Licensing
> 
> Furthermore, the Feedback button on the side, shifts to the footer area
> 
>  Screen.Recording.2024-07-23.180103.mp4

At what width do you expect the hamburger to show up?

**Comment by VijaySamant4368** [comment]
> > When the width is less than 1100px, the following links go inside hamburger:
> > 
> > * Home
> > * About Us
> > * FAQs
> > * Contributions
> > * Let's Go
> > * How to Play
> > * Terms of Service
> > * Privacy Policy Licensing
> > 
> > Furthermore, the Feedback button on the side, shifts to the footer area
> > Screen.Recording.2024-07-23.180103.mp4
> 
> At what width do you expect the hamburger to show up?

1100px

**Comment by Lovelyfin00** [comment]
> At 625px, the Discord and Github links go inside the hamburger menu. At 500px, the Feedback button also go inside the Hamburger menu.
> 
>  Screen.Recording.2024-07-23.180641.mp4

What fix would you prefer?
For those links to be at the footer but break to the next line?

**Comment by VijaySamant4368** [comment]
> > At 625px, the Discord and Github links go inside the hamburger menu. At 500px, the Feedback button also go inside the Hamburger menu.
> > Screen.Recording.2024-07-23.180641.mp4
> 
> What fix would you prefer? For those links to be at the footer but break to the next line?

I believe that it will make the footer unnecessarily wide(more area in y-direction).

**Comment by Lovelyfin00** [comment]
> > > When the width is less than 1100px, the following links go inside hamburger:
> > > 
> > > * Home
> > > * About Us
> > > * FAQs
> > > * Contributions
> > > * Let's Go
> > > * How to Play
> > > * Terms of Service
> > > * Privacy Policy Licensing
> > > 
> > > Furthermore, the Feedback button on the side, shifts to the footer area
> > > Screen.Recording.2024-07-23.180103.mp4
> > 
> > 
> > At what width do you expect the hamburger to show up?
> 
> 1100px

I don't think leaving it this way is an issue. The reason why the hamburger shows up is because there's no more space available from that width for the nav links. If we use 1100, it's going to look compressed

**Comment by VijaySamant4368** [comment]
Though if you prefer it, I can make the links to go to the next line with some changes in the code.

**Comment by Lovelyfin00** [comment]
> > > At 625px, the Discord and Github links go inside the hamburger menu. At 500px, the Feedback button also go inside the Hamburger menu.
> > > Screen.Recording.2024-07-23.180641.mp4
> > 
> > 
> > What fix would you prefer? For those links to be at the footer but break to the next line?
> 
> I believe that it will make the footer unnecessarily wide(more area in y-direction).

What would?
Breaking it to another line would make the footer longer. We can leave this since its not breaking anything

**Comment by VijaySamant4368** [comment]
> > > > When the width is less than 1100px, the following links go inside hamburger:
> > > > 
> > > > * Home
> > > > * About Us
> > > > * FAQs
> > > > * Contributions
> > > > * Let's Go
> > > > * How to Play
> > > > * Terms of Service
> > > > * Privacy Policy Licensing
> > > > 
> > > > Furthermore, the Feedback button on the side, shifts to the footer area
> > > > Screen.Recording.2024-07-23.180103.mp4
> > > 
> > > 
> > > At what width do you expect the hamburger to show up?
> > 
> > 
> > 1100px
> 
> I don't think leaving it this way is an issue. The reason why the hamburger shows up is because there's no more space available from that width for the nav links. If we use 1100, it's going to look compressed

So I should make the footer links go to the next line, but the header links should go inside the hamburger menu?

**Comment by Lovelyfin00** [comment]
No
Let's leave it the way it is right now
It's not breaking anything
What you should think about is making the content responsive.
Like the form and the instruction section

**Comment by VijaySamant4368** [comment]
@Lovelyfin00 I noticed that in the newer version of the repo, the homepage is more or less made more responsive, and has the same behavior as I made it to be. So should I drop this issue, or is there anything else you wish me to do?

**Comment by Lovelyfin00** [comment]
> @Lovelyfin00 I noticed that in the newer version of the repo, the homepage is more or less made more responsive, and has the same behavior as I made it to be. So should I drop this issue, or is there anything else you wish me to do?

We might have to close this pr

**Comment by VijaySamant4368** [comment]
@Lovelyfin00 please have a look at the latest version of the homepage first.

**Comment by Lovelyfin00** [comment]
It still looks broken
<br/>
<br/>

image

**Comment by VijaySamant4368** [comment]
I was starting to think the problem was with my device.
Before the last set of merging, the webpage was looking good, and even responsive up to a limit. 
The problem I think is that there are too many contributors who are having conflicts and are just doing whatever they want when resolving them.

**Comment by Lovelyfin00** [comment]
> I was starting to think the problem was with my device. Before the last set of merging, the webpage was looking good, and even responsive up to a limit. The problem I think is that there are too many contributors who are having conflicts and are just doing whatever they want when resolving them.

Yesss
It looks even more broken than when we checked it the last time.

**Comment by VijaySamant4368** [comment]
Ok, I will try my best to make it look better.

**Comment by Lovelyfin00** [comment]
> Ok, I will try my best to make it look better.

Someone else has already opened a PR to fix that

**Comment by VijaySamant4368** [comment]
I think it would be better for me to open a completely new pr.

**Comment by VijaySamant4368** [comment]
> > Ok, I will try my best to make it look better.
> 
> Someone else has already opened a PR to fix that

All right.

**Pull request closed without merging**
