### PR TITLE
files upload

### PR DESCRIPTION
**Pull request by aswin98855**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes # <162>

<hr>
 
## Mark the task you have completed ✅

- [✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by aswin98855** [comment]
@Lovelyfin00 

Now it is working i think...You can check it now

**Comment by Lovelyfin00** [comment]
The css is still broken

**Comment by Lovelyfin00** [comment]
> https://github.com/aswin98855/Dot-Box/tree/ranking_new
> 
> In my repository there are no issues found...

Its nor working
Have you run it while on this branch and tested it?
Send screenshot of how it looks while you'r on this ranking_new branch

**Comment by Lovelyfin00** [comment]
You need to use git and clone it to your pc

**Comment by Lovelyfin00** [comment]
https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository

**Pull request closed without merging**
