### PR TITLE
Enhanced The Timer Functionality and Restore the Game Interface

### LINKED ISSUE #631: [Bug]: Tour Guide Broke By The Recent Chnages
### Give a brief about the bug ✍️

Hey @ayush-t02 

The recent PR related to Timer has broke the code of the Tour steps leading to disfunctionality 

The alignments and logic and its scripts are completely broke and gone out of the body of the website 

image

It also affect the responsivness of the tour step

image

Additinally ,
The timer should properly fixed in mobile view and any other devices It is overlapping the entire game interface 

image

### What is the expected behavior? 🤔

Each component should work without affecting the website's responsiveness and overlapping each other

### Provide step by step information reproduce the bug 📄

N/A

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by MastanSayyad**
## PR Description 📜

Hey @ayush-t02 

Issue fixes #631

I have Fix the Issues in the game interface and Enhanced the timer functionality
- To make it easily accessible (in Both mobile and desktop view)
- Made required adjustments to avoid overlapping on the game board
- Fix the Code overflow from the body 
- Added additional tour step introducing Timer functionality
- FIx the alignments and the positioning of tour steps with the new changes 

image

image

image

image

image

I have ensure each game component does not overlap with each other and work independently!

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by MastanSayyad** [comment]
Hey @ayush-t02 I have fixed the issue and ensured the timer or any other component functionality does not overlap

**Comment by MastanSayyad** [comment]
@ayush-t02 pls take a look at this pr and review it!

**Comment by ayush-t02** [comment]
resolve conflicts

**Comment by MastanSayyad** [comment]
@ayush-t02 I have resolved the conflicts

**Comment by MastanSayyad** [comment]
Also, remove the level 3 label as I think someone fixed the breaking issue before me so the only work I have done is to enhance the timer functionality, and its position and add a new tour step introducing the timer and some other changes so I should get only level 2 for this. just to keep it fair! @ayush-t02

**Pull request merged**
