### PR TITLE
Added exit button on the game

### PR DESCRIPTION
**Pull request by 3simransharma**
## PR Description 📜

I have added exit button in the game, it'll be easy and user-friendly for the players to exit from the game.

<hr>

### CODE REVIEW

**Comment by Lovelyfin00** [comment]
Add a video or screenshot of your PR

**Comment by 3simransharma** [comment]
Sure, this is the video showing the feature I have added for this website: 
https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/95140559/e2b1cb62-a2e2-421a-8f58-2876d665f5b0

**Comment by Lovelyfin00** [comment]
This is a good idea. The button is too close to the edge. You should move it closer. Also, can you resolve the merge conflict, if yes please do that. I'd like you to add border-radius to the button of lets say 5 or 8 depending on which one looks better

**Comment by ayush-t02** [comment]
there is a conflict with game.js, please resolve it

**Pull request closed without merging**
