### PR TITLE
fixed reset button issue no. #391

### PR DESCRIPTION
**Pull request by Aradhyajha**
## PR Description 📜

Fixes # 391

"fixed reset button by changing some code in index.html and index.js"

### CODE REVIEW

**Comment by ayush-t02** [comment]
resolve conflicts and add a demo video

**Comment by Aradhyajha** [comment]
https://github.com/ChromeGaming/Dot-Box/assets/130289875/b991819f-5824-4fab-9cf9-0ca8f86529fc

@ayush-t02 .. sir before i made the changes  while clicking on  the reset button it  automatically set to empty one but after i made the changes the no. of rows and columns  equal to 6 as set to the default one... please u check  the video once..

**Comment by ayush-t02** [comment]
why have you closed the PR?

**Comment by Aradhyajha** [comment]
Sir may I raise the pr again

**Comment by Aradhyajha** [comment]
Sir can you please give some suggestions regarding this

**Comment by ayush-t02** [comment]
create a new issue -> create a new PR for new issue

**Comment by Aradhyajha** [comment]
Sir for solving the reset button may I need to create new issue

**Pull request closed without merging**
