### PR TITLE
Removed Dissortion

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
I Removed Dissortion in Footer - Solved #711 
Kindly go through this PR  @ayush-t02 

bb

### CODE REVIEW

**Comment by ayush-t02** [comment]
what exactly has been done here?

**Comment by ayush-t02** [comment]
I feel a lot of info is present in the footer. best approach would be to restyle the footer to handle all the links and info, preferably multi-line footer

**Comment by sailaja-adapa** [comment]
I am sorry @ayush-t02 it is my first time contributing to open source so I thought I should remove the overlapping between chrome gaming and other social links and I thought I should give good padding between footer links

**Comment by sailaja-adapa** [comment]
Can you explain me briefly what should I need to do? @ayush-t02

**Comment by ayush-t02** [comment]
@sailaja-adapa hey sailaja no need to be sorry, we are all learning here and that is the entire point of GSSoC. all I said above is that the footer looks shabby as of now so you should try to change the design to make it look less congested but since today is the last day of contribution I'll merge this PR. 

but do continue to pursue open-source.

**Comment by sailaja-adapa** [comment]
Yeah okk Thank you @ayush-t02

**Pull request merged**
