### PR TITLE
added timelimit for each player

### PR DESCRIPTION
**Pull request by KARTHIK174**
I have added timelimit for each player.when the time is over then the turn goes to next player.

## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes # <your_issue_number>
#105 #75 
<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅] I have performed a self-review of my own code or work.
- [ ✅] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [ ✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

Screenshot 2024-05-17 125356

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by Durgesh4993 — COMMENTED** [review]
Add a demo video and resolve conflict file

**Comment by KARTHIK174** [comment]
> Add a demo video and resolve conflict file


https://github.com/ChromeGaming/Dot-Box/assets/107982190/5d050557-385e-43a3-9195-1ffc6bf741e5

**Comment by Durgesh4993** [comment]
@KARTHIK174 Still showing conflicts

**Comment by KARTHIK174** [comment]
@Durgesh4993 I have resolved the conflicts once check it and let me know.

**Comment by KARTHIK174** [comment]
@Durgesh4993 I have resolved the conflicts.

**Comment by Durgesh4993** [comment]
@KARTHIK174 Please add a demo vedio

**Pull request merged**
