### PR TITLE
✔️Implemented Dedicated "Testimonials Page" For DotBox

### LINKED ISSUE #698: 🎮Implement a "Dedicated Testimonials" Page! 🗨️
### 🎮 feature Request

Hey @ayush-t02 

I propose to make a testimonial page to the Dot Box game website. 

This page will have Some **Already Submitted Testimonials from existing players** and **will allow players to share their feedback and experiences with the game**.  

### Here’s what I plan to do 
- I will **create a new page dedicated** to player testimonials (For ex, "What Our Players Say!🌟)
- This will **include sections for "displaying existing testimonials"**
- A **form for users** to **"submit their own testimonial"**. ✅
- The submission option will provide a way for players to contribute their thoughts easily.
- **Like/Dislike Buttons:** Allow users to like or dislike testimonials.  👍👎
- The Review they give, ,will also reflect in **a default Star Rating they gave Aside the Player's Logo.**
- The Profile's of the Players will be Better suitable to a player.
- **Responsive Design:** Ensure the page is mobile-friendly so users can easily view and submit testimonials from any device.

 ### Why this is needed
 A testimonial page **will help us showcase positive player experiences** and build a stronger community. It **will also encourage new players** to try the game based on real user feedback.

**Below is the Example I just made in dotbox as a demo to show you... I will make it better in real implementaiton**
image

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @ayush-t02 
issue closes #698 

I have implemented a dedicated testimonials page for the website.

### Here's What I Did - 
1. **Designed a Dedicated "Testimonials" Page**
2. Made sure the page **follows the Website's Game theme** 
3. Moreover, **I made it "Fully-Responsive" For all the screen sizes**
4. **Added "Floating Animations" to each card** which is a better functionality
5. I have **added Different testimonials cards** which gives individuals thoughts about there gaming experience 
6. I have **added hovering effects to each**, it's image too
7. **Added Text-Shadows** to highlight the main effects
8. **Applied Suitable padding and margin** to each card to maintain consistency 
9. Additionally, **I have added a favicon** to it.
image

- Also, Integrated a working navbar in it to avoid further issues 

**Here's the Video -** 

https://github.com/user-attachments/assets/af6db747-f540-4e39-8d73-6df9be34ab77

@ayush-t02 **Here's the responsiveness -** 

image

Please take a look!
thankyou!

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by aslams2020** [comment]
@ayush-t02 Please review this.

**Comment by aslams2020** [comment]
@ayush-t02 If possible, can you please increase the Level? 
as the PR includes Responsiveness too and integrated navbar with ham-menu..

can you please review it again.?

**Comment by aslams2020** [comment]
> @ayush-t02 If possible, can you please increase the Level? as the PR includes Responsiveness too and integrated navbar with ham-menu..
> 
> can you please review it again.?

@ayush-t02

**Comment by ayush-t02** [comment]
@aslams2020 as a web developer responsiveness is always a part of whatever work you do. Fixing something unresponsive is a whole different thing.

**Comment by ayush-t02** [comment]
as for the navbar, it is already present, you could've just used the same component instead of building it again

**Pull request merged**
