### PR TITLE
Added Ranking Functionality

### LINKED ISSUE #162: [Enhancement]: Giving Rank for players while playing
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement

I want to add Ranking of the players based on their points. Ranks will be changed when the points are changed.

image

Based on above image the ranking order will be :

Rank       Players
1             Player-3
2             Player-5
3             Player-6
4             Player-1
5             Player-2
6             Player-4

In 4,5,6 positions, the rank will be given in the order of players.

Please assign this issue to me under gssoc24

### Describe the solution you'd like

Solution steps:

Initially Ranks are given in player number order.

When players are playing, While they are gaining points, The rank for that players will be changed. Based on the points the rank will be given. The players with highest points is ranked 1 and so on. If players having same points, The rank will be given in the order of players.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by aswin98855**
## PR Description 📜
Fixes #162 

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below

From the Image I uploaded below, The scores of individual players are displayed in the side of game board. From that we can say the status of players, that means we can know the position of standings for each individual Player.
<hr>
 
## Mark the task you have completed ✅

- [✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [✅ ] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

Screenshot 2024-05-21 172441

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Lovelyfin00** [comment]
Hi @aswin98855 
Fix the merge conflict then I'd review

**Comment by Lovelyfin00** [comment]
Hi @aswin98855 
Fix the merge conflict then I'd review

**Comment by aswin98855** [comment]
I fixed the merge conflict

**Comment by Lovelyfin00** [comment]
@aswin98855 
Merge conflict still shows up. Tag me when you've fixed it. Include a video demo in this pr if possible> I'll test and merge as soon as its done

**Comment by aswin98855** [comment]
@Lovelyfin00  

I fixed the merge conflict. It was showing like "**This branch has no conflicts with the base branch**". 

I included a video demo of it please look into it..


https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/116991167/e69c7adf-769b-497c-b238-367a149d9166

**Pull request closed without merging**
