### PR TITLE
Revert "Adding Chatbot and home icon to every Page"

### PR DESCRIPTION
**Pull request by ayush-t02**
Reverts ChromeGaming/Dot-Box#529

this PR breaks the UI structure of the website

### CODE REVIEW

**Comment by Ojas-Arora** [comment]
@ayush-t02 What was the problem in my commits ? I would like to try again to add the same in the website.

**Comment by ayush-t02** [comment]
the entire hero section was broken via your PR which was recently fixed

**Comment by Ojas-Arora** [comment]
@ayush-t02 Should I try it again to make my changes without affecting hero section as there is no chatbot and home icon present now.

**Comment by ayush-t02** [comment]
yes you may try again, just make sure to not break any aspect of the current webapp.

**Comment by Ojas-Arora** [comment]
@ayush-t02 Ok

**Pull request merged**
