### PR TITLE
Theme change

### LINKED ISSUE #412: [Bug]: Theme not changing and no theme works on the game page
### Give a brief about the bug ✍️

The theme is not changing in the homepage. There is no theme visible in the gamepage.

### What is the expected behavior? 🤔

The theme should change when a different theme is selected. Add atleast 3 themes.

### Provide step by step information reproduce the bug 📄

Just launch the application and try to change the theme via dropbox.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by hars-21**
## PR Description 📜

Added themes to index and games page. With the same theme. Fully functional themes. 
New themes can be added without much interference.

Fixes #412  

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

Screen Shot 2024-07-07 at 7 28 29 PM
Screen Shot 2024-07-07 at 7 28 41 PM
Screen Shot 2024-07-07 at 7 28 48 PM
Screen Shot 2024-07-07 at 7 28 52 PM

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by ayush-t02** [comment]
resolve conflicts

**Comment by hars-21** [comment]
@ayush-t02 Conflicts has been resolved. Please review!

**Comment by ayush-t02** [comment]
still conflicts are present, look into it

**Comment by hars-21** [comment]
Resolved!!

**Pull request merged**
