### PR TITLE
Reorganised all files into separate folders

### LINKED ISSUE #444: [New Feature]: Reorganise the files in main repo into separate folders
### Enchancement

The files are currently just randomly cluttered in main repo which mkes is absolutely terrible to access a particular file, i want to separate the html css and js files into separate folders so they are easy to access

### Point down the features

feature points - ease of access and increased readability

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by partha120804**
## PR Description 📜

Reorganized all the files that were cluttered into separate folders, and handled all the references inside all the files.

## Related Issue 
Closes #444 

## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

## Add your screenshots(Optional) 📸
image

### CODE REVIEW

**Comment by partha120804** [comment]
@ayush-t02 Please review and merge this PR, as this will help the contributors to easily make contributions.

**Comment by ayush-t02** [comment]
are you adding this as a GSSoC  contribution?

**Comment by partha120804** [comment]
yes please refer issue #444

**Comment by ayush-t02** [comment]
1. resolve conflicts.
2. Do not add PRs if issue is not assigned.

**Comment by partha120804** [comment]
1. conflict resolved 👍🏻 
2. okay

**Pull request merged**
